#!/bin/bash

COPIED_FILE_PATH="$1"

ORIGINAL_FILE_ROOT=~/storage/dcim

process() {
    local COPIED_FILE_PATH="$1"
    local DEST_FULL_PATH="$2"
    echo "Processing $DEST_FULL_PATH"
    identify -format "Resolution: %wx%h (%[fx:w*h/1000000] MP)\nSize: %b\n" "$DEST_FULL_PATH"
    local CURR_TITLE=$(exiftool -s3 -xmp-dc:title "$DEST_FULL_PATH")
    local CURR_PEOPLE_LIST=$(exiftool -s3 -PersonInImage "$DEST_FULL_PATH")

    echo
    echo "Specify title for $DEST_FULL_PATH;"
    echo "  add a trailing ' qXX' to trigger recompression at quality XX (10-99)"
    read -e -i "$CURR_TITLE" -p "> " NEW_TITLE_WITH_OPT_Q
    local COMP_QUALITY=$(echo $NEW_TITLE_WITH_OPT_Q | grep -o ' q[1-9][0-9]$' | grep -o '[1-9][0-9]')
    local NEW_TITLE=$(echo $NEW_TITLE_WITH_OPT_Q | sed 's/ q[1-9][0-9]$//')
    echo
    echo "New title: $NEW_TITLE"

    read -e -i "$CURR_PEOPLE_LIST" -p "', '-delimited people list (can be empty)> " NEW_PEOPLE_LIST

    if [[ "$COMP_QUALITY" != "" ]]; then
        echo "New quality: $COMP_QUALITY"
        convert "$COPIED_FILE_PATH" -quality $COMP_QUALITY "$DEST_FULL_PATH"
        local NEW_FILE_SIZE=$(stat -c%s "$DEST_FULL_PATH")
        echo "New size: $NEW_FILE_SIZE"
    else
        echo "Not recompressing"
    fi
    rm "$COPIED_FILE_PATH"

    local TITLE_PARAMS=( -xmp-dc:title="$NEW_TITLE" )
    local PEOPLE_PARAMS=( -PersonInImage="$NEW_PEOPLE_LIST" )
    

    local PARAMS=( -overwrite_original_in_place )
    local EXIF_CHANGE=false

    if [[ "$NEW_TITLE" != "$CURR_TITLE" ]]; then
        echo "Updating title to $NEW_TITLE..."
        local PARAMS+=( "${TITLE_PARAMS[@]}" )
        EXIF_CHANGE=true
    fi
    if [[ "$CURRPEOPLE_LIST" != "$NEW_PEOPLE_LIST" ]]; then
        echo "Updating people to $NEW_PEOPLE_LIST..."
        local PARAMS+=( "${PEOPLE_PARAMS[@]}" )
        EXIF_CHANGE=true
    fi
    if [[ "$EXIF_CHANGE" == "true" ]]; then
        exiftool "${PARAMS[@]}" "$DEST_FULL_PATH"
        echo "Done updating."
    fi
    echo Done processing.
}


BASENAME=`basename $COPIED_FILE_PATH`
FILES_WITH_SAME_NAME_IN_DCIM=$(find -H "$ORIGINAL_FILE_ROOT" -name "$BASENAME")

NUM_MATCHES=$(echo "$FILES_WITH_SAME_NAME_IN_DCIM" | wc -l)

if [ $NUM_MATCHES -eq 1 ]; then
    ORIGINAL_FILE="${FILES_WITH_SAME_NAME_IN_DCIM[0]}"
    process "$COPIED_FILE_PATH" "$ORIGINAL_FILE"
else
    echo "Either no files or multiple files found."
    echo "Matches: ${FILES_WITH_SAME_NAME_IN_DCIM[@]}"
fi
